### ISSUE TITLE
No module neuralcoref.conllparser error

### ISSUE THREAD

**Issue by pdhung3012** [huggingface/neuralcoref#130]
Hello. I use python 2.7 and spacy 2.0.12. I finished install neuralcoref 3.1. I got this error when trying to run the data:

 python2 -m neuralcoref.conllparser --path /home/hung/git/neuralcoref/data/conll-2012-train.v4/conll-2012/v4/data/train/
/home/hung/anaconda3/envs/py27/bin/python2: No module named neuralcoref.conllparser

I have stucked with this error for a day. Thanks for your help.

**Comment by felialois** [comment]
I have exactly the same error and cannot find a solution. If you find anything please post it for others that might have the same problem. Thanks

**Comment by pdhung3012** [comment]
I think the problem is that neural coref doesn't include the conllparser.py when it built. My solution is that I ran the conllparser directly instead (with assigning the --path to your training folder).
To run the conllparser.py directly, you need the fix the import statement from several file (conllparser, compat and document.py)

**Comment by pdhung3012** [comment]
> I have exactly the same error and cannot find a solution. If you find anything please post it for others that might have the same problem. Thanks

Hello. I think you might want to use the release of neural coref that have the training code instead. It might embed the training code instead of the lastest 3.0

**Comment by thomwolf** [comment]
Yes, the training scripts are out-dated for now. Updating then is next on my to-do list but I don't have an ETA for the moment.

**Comment by svlandeg** [comment]
Fixed by PR #211

**Comment by wanxinxie** [comment]
> I think the problem is that neural coref doesn't include the conllparser.py when it built. My solution is that I ran the conllparser directly instead (with assigning the --path to your training folder).
> To run the conllparser.py directly, you need the fix the import statement from several file (conllparser, compat and document.py)
@pdhung3012 Hi, I'm trying to run the conllparser.py directly as well, but there is still an error: No module named conllparser. Do you mind elaborate on how to fix the import statement from the other files (conllparser, compat and document.py)? I check the file in compat, document and utils but I don't find anywhere include "import conllparser" (I assume that maybe somewhere in the code exists this line so that there is such error). Thank you so much!
